### ISSUE TITLE
Update kernel sources for CE4 to CPH2613_14.0.1.704(EX01)

### ISSUE THREAD

**Issue by Venkat3620** [OnePlusOSS/android_kernel_oneplus_sm7550#1]
@OnePlusOSSAdmin 

this repo hasnt been updated in a while, the phone got few updates,
currently its on CPH2613_14.0.1.704(EX01). So please update this kernel to the latest on at the time of pushing source code.
update modules repo as well.

**Comment by OnePlusOSSAdmin** [comment]
updated

**Comment by Venkat3620** [comment]
Thanks for quick response
